### ISSUE TITLE
`make` fails with default build

### ISSUE THREAD

**Issue by bacongobbler** [deis/pkg#13]
If you try the following in a container for a scratch environment, I find that `make build` fails (NOTE: must be running docker locally for the volume mount to work. docker-machine and boot2docker users will need to clone the repo inside the container):

```
docker run -itv $GOPATH/src/github.com/deis/pkg:/go/src/github.com/deis/pkg golang:1.5 bash
cd /go/src/github.com/deis/pkg
wget https://github.com/Masterminds/glide/releases/download/0.8.3/glide-0.8.3-linux-amd64.tar.gz -O - | tar -xz
mv linux-amd64/glide /usr/local/bin/ && rm -rf linux-amd64
glide up
make
```

Running `make test` works without issue, but [`make build` doesn't](https://travis-ci.org/deis/pkg/jobs/105300351). This was found out while trying to implement #12.

**Comment by arschles** [comment]
would #14 fix this?

**Comment by bacongobbler** [comment]
I think it has something to do with the glide dependencies. Not sure.
