### ISSUE TITLE
add to CI

### ISSUE THREAD

**Issue by arschles** [deis/pkg#16]
after #15 is done, this will have to be re-added to CI, since the dockerized build process requires a `.travis.yml` file similar to [this one](https://github.com/deis/builder/blob/master/.travis.yml) (except without the deployment part)

**Comment by bacongobbler** [comment]
We're already on CI! https://github.com/deis/pkg/blob/master/.travis.yml

Do you mean to track this as part of #15?

**Comment by sgoings** [comment]
We probs need to add a Travis badge to the repo to make sure that the CI build status more noticed.

**Comment by arschles** [comment]
@bacongobbler originally, I meant this to be the counterpart for #15, since the changes to the `.travis.yml` would be non-trivial. Now that you mention it, though, you're probably right, I should just merge this with #15, because #15 will break CI without said changes.

@sgoings see https://github.com/deis/pkg/issues/17

Closing.
