### ISSUE TITLE
aboutme.FromEnv() fails in deis/minio

### ISSUE THREAD

**Issue by arschles** [deis/pkg#8]
An error was observed in a production minio pod, against `deis/pkg` version ee60d947fecd410bd9ea30ffb53f9ea3e6dc038e. More details at https://github.com/deis/minio/pull/39.

Note: the bug in deis/minio#39 was fixed by rolling back to an older, known-working version of about me so this is not being labelled showstopper.

**Comment by kmala** [comment]
aboutme is working correctly. minio is not setting the namespace correctly and hence can't find the pod.
https://github.com/deis/charts/pull/347
